### ISSUE TITLE
Wrong validation error on return variables

### ISSUE THREAD

**Issue by colameo** [Yakindu/solidity-ide#111]
![solidity_wrong_validation](https://user-images.githubusercontent.com/629760/39116886-d8ac4fd8-46e5-11e8-8a22-00fb7a906ad0.jpg)
[see also](https://remix.ethereum.org/#optimize=false&version=soljson-v0.4.23+commit.124ca40d.js)

**Comment by andreasmuelder** [comment]
I think this is already fixed on master with latest SCT release. Which version did you use?

**Comment by andreasmuelder** [comment]
Fixed with the latest release
