### ISSUE TITLE
Warning during rename refactoring

### ISSUE THREAD

**Issue by andreasmuelder** [Yakindu/solidity-ide#156]
When rename refactoring is used, a warning pops up with "misconfigured language"
However, the rename refactoring works.

![missconfigured_language](https://user-images.githubusercontent.com/6338708/45378479-d7ff8280-b5fd-11e8-9e27-3dca882ed6a1.png)

**Comment by flantony** [comment]
Implementation hint:
https://github.com/eclipse/xtext-eclipse/issues/317

**Comment by andreasmuelder** [comment]
Seems to be fixed in new Photon / Xtext 2.14 based product
