### ISSUE TITLE
Provide language server extension for VSCode

### ISSUE THREAD

**Issue by kthoms** [Yakindu/solidity-ide#192]
The Solidity language should be made available for VSCode. Therefore a language server has to be build from the DSL implementation and packaged into a VSCode extension project.

The new extension should be made available in the VSCode marketplace.

**Comment by andreasmuelder** [comment]
Is there any drawback if we stay in socket mode but launch the solidity-ls server before connecting to it?

**Comment by cdietrich** [comment]
If we ship the extension to users eg via the vscode marketplace the socket approach is not feasable imho

**Comment by andreasmuelder** [comment]
https://github.com/Yakindu/solidity-ide/pull/203 works from the debug instance of VSCode but not with the installed vsix extension for some reason

**Comment by cdietrich** [comment]
Did you check the folder structure in .vscode in home dir

**Comment by andreasmuelder** [comment]
seems to be the same as in your example https://github.com/cdietrich/xtext-languageserver-example

we do not have the settings.json but I don't know if we need this
"typescript.tsdk": "./node_modules/typescript/lib"

**Comment by andreasmuelder** [comment]
switch to standalone communication with https://github.com/Yakindu/solidity-ide/pull/203
