### ISSUE TITLE
Failed to create injector for com.yakindu.solidity.Solidity

### ISSUE THREAD

**Issue by erikvaningen** [Yakindu/solidity-ide#224]
When making a new solidity file, that wizard reported this error:
**The selected wizard could not be started.
Failed to create injector for com.yakindu.solidity.Solidity (occurred in com.yakindu.solidity.ui.SolidityExecutableExtensionFactory)
Failed to create injector for com.yakindu.solidity.Solidity**

**Comment by kthoms** [comment]
How did you install Solidity? What is your base eclipse version? Please provide the full stack.

**Comment by andreasmuelder** [comment]
Thank you very much, I tracked it down to some incompatibilities with the latest release of YAKINDU Base Feature. 

I will redeploy the update site once it is built.
