### ISSUE TITLE
[Language Server] LS must not contain UI bundles

### ISSUE THREAD

**Issue by kthoms** [Yakindu/solidity-ide#242]
The language server application built contains some UI bundles, e.g. org.eclipse.ui or org.eclipse.swt. This inidcates that there are some dependency issues with solidity.ide. The resulting application built should not contain them.

<img width="598" alt="screenshot 22" src="https://user-images.githubusercontent.com/265597/52174908-37bc1d00-279b-11e9-9c06-8ab72da2c16b.png">

**Comment by nyssen** [comment]
It seems this is introduced through a dependency from com.yakindu.solidity.compiler to org.eclipse.xtext.ui.

**Comment by nyssen** [comment]
The SolidityMarkerCreator extends MarkerCreator, which is provided by org.eclipse.xtext.ui.editor.

**Comment by andreasmuelder** [comment]
@flantony can we move the marker creator to the solidity.ui bundle?
