### ISSUE TITLE
source code 

### ISSUE THREAD

**Issue by XiaoXiaoYi123** [Yakindu/solidity-ide#248]
I am very interest this tool,But when I tried to read the source code,I met some problems.
I sincerely hope to get your help.
The problem is this:
I found that the diagram is stored in .sct files, and when i opened the file, i found it is a xmi file, I didn't know how this xmi files was formed. And I tried to look for information and ask classmates ,but I still did not solve this problrm. Could you help me to solve this problem?
I will be very happy if I hear from you.
Thank you all the same

**Comment by BeckmaR** [comment]
Hey @XiaoXiaoYi123! `sct` files are statecharts, created with another tool made by the YAKINDU organization, the YAKINDU Statechart Tools. You can use it to take a look at the diagrams, [get it here.](https://info.itemis.com/state-machine/download-yakindu-statechart-tools) Initially, you'll have a trial license for 30 days, but you can apply for an academic license if you are a student, and opening statecharts is always possible, even without a license - just not editing.

If you have questions about YAKINDU Statechart Tools, head over to the [User group](https://groups.google.com/forum/embed/#!forum/yakindu-user). If you find a bug, [here is its repository](https://github.com/Yakindu/statecharts).

I'm closing this as unrelated to solidity.

**Comment by XiaoXiaoYi123** [comment]
I am very sorry that I may not have explained clearly the problem I want to consult.I was interested in this software, so I installed the yakindu software from the source code, and I wanted to get the whole software architecture straight. So the first step, I want to start by looking at the.sct file. When I open the.sct file, I find that it is in xmi format. On the one hand, I tried to search the Internet for answers, but nothing came out. On the other hand, I started scanning the source code of yakindu without having a clue. So I want to ask you this question.I know it's presumptuous, but I'm still begging you to help me with this problem.
I will be very happy if I hear from you.
Thank you all the same

**Comment by BeckmaR** [comment]
I am sorry, but I don't understand your confusion. As stated above, you'll need to install another tool, YAKINDU Statechart Tools, to view the sct files. They are graphical diagrams. But as far as I can tell, they are only used in some examples that demonstrate how to generate a smart contract from such a statechart, so you probably don't even need them to understand the software.
