### ISSUE TITLE
Updating the Xtext Community Website

### ISSUE THREAD

**Issue by miklossy** [Yakindu/solidity-ide#320]
Hello Yakindu Solidity IDE team,

The Xtext team would like to update the [Xtext community website](https://www.eclipse.org/Xtext/community.html) listing all the cool projects people are building around Xtext/Xtend.

See also the corresponding [GitHub issue](https://github.com/eclipse/xtext/issues/1541) and [Bugzilla ticket](https://bugs.eclipse.org/bugs/show_bug.cgi?id=328477).

If you are interested that the Yakindu Solidity IDE project is listed there, please provide the following information as a comment to this issue:

```
<tr>
	<td><a href="project_link">project_name</a></td>
	<td>project_description_max_2_sentences</td>
	<td>license</td>
	<td>category</td>
	<td>author(s)</td>
</tr>

```
We will then update the Xtext community website and get it online as soon as possible.

Thanks!
Tamás

**Comment by miklossy** [comment]
I would like to add the `YAKINDU Solidty IDE` project to the [Xtext community website](https://www.eclipse.org/Xtext/community.html) as follows:

```html
<tr>
	<td><a href="https://github.com/Yakindu/solidity-ide">YAKINDU Solidity IDE</a></td>
	<td>The free to use, open source YAKINDU Solidity IDE provides an Xtext-based integrated development environment for ethereum / solidity based smart contracts. It can be installed in different environments, such as Atom, Eclipse, Theia and VsCode.  <a href="https://solidity-ide.itemis.de/">Online editor</a> and <a href="https://yakindu.github.io/solidity-ide/">documentation</a>.</td>
	<td>EPL 1.0</td>
	<td>Tool</td>
	<td>Andreas Mülder, Alexander Nyssen, Florian Antony, et al. </td>
</tr>
```

@nyssen @andreasmuelder Do you agree with that?

**Comment by andreasmuelder** [comment]
@miklossy yes, perfect, thank you.

**Comment by miklossy** [comment]
The `YAKINDU Solidity IDE` project has been added to the [Xtext community website](https://www.eclipse.org/Xtext/community.html).
