### ISSUE TITLE
Installation via marketplace does not work

### ISSUE THREAD

**Issue by svenjawendler** [Yakindu/solidity-ide#77]
I have this problem (Win 7 64Bit, Eclipse Oxygen,: 
Cannot complete the install because of a conflicting dependency.
  Software being installed: Solidity Editor Feature 0.7.0.201712011232 (com.yakindu.solidity.feature.feature.group 0.7.0.201712011232)
  Software currently installed: Eclipse Java Development Tools 3.13.1.v20171009-0410 (org.eclipse.jdt.feature.group 3.13.1.v20171009-0410)
  Only one of the following can be installed at once: 
    Object Teams Development Tooling Core 3.12.2.v_OTDT_r252_201612071657 (org.eclipse.jdt.core 3.12.2.v_OTDT_r252_201612071657)
    Java Development Tools Core 3.13.50.v20170926-1643 (org.eclipse.jdt.core 3.13.50.v20170926-1643)
    Java Development Tools Core 3.12.0.v20160516-2131 (org.eclipse.jdt.core 3.12.0.v20160516-2131)
    Object Teams Development Tooling Core 3.12.3.v_OTDT_r253_201703071318 (org.eclipse.jdt.core 3.12.3.v_OTDT_r253_201703071318)
    Java Development Tools Core 3.13.0.v20170516-1929 (org.eclipse.jdt.core 3.13.0.v20170516-1929)
    Java Development Tools Core 3.13.50.v20171007-0855 (org.eclipse.jdt.core 3.13.50.v20171007-0855)
    Object Teams Development Tooling Core 3.12.0.v_OTDT_r250_201606070956 (org.eclipse.jdt.core 3.12.0.v_OTDT_r250_201606070956)
    Java Development Tools Core 3.12.3.v20170228-1205 (org.eclipse.jdt.core 3.12.3.v20170228-1205)
    Object Teams Development Tooling Core 3.12.1.v_OTDT_r251_201609131451 (org.eclipse.jdt.core 3.12.1.v_OTDT_r251_201609131451)
    Object Teams Development Tooling Core 3.13.0.v_OTDT_r260_201706061122 (org.eclipse.jdt.core 3.13.0.v_OTDT_r260_201706061122)
    Java Development Tools Core 3.12.2.v20161117-1814 (org.eclipse.jdt.core 3.12.2.v20161117-1814)
    Java Development Tools Core 3.14.0.v20171025-0549 (org.eclipse.jdt.core 3.14.0.v20171025-0549)
    Java Development Tools Core 3.12.1.v20160829-0950 (org.eclipse.jdt.core 3.12.1.v20160829-0950)
  Cannot satisfy dependency:
    From: Solidity Editor Feature 0.7.0.201712011232 (com.yakindu.solidity.feature.feature.group 0.7.0.201712011232)
    To: org.eclipse.jdt.core [3.14.0.v20171025-0549]
  Cannot satisfy dependency:
    From: Eclipse Java Development Tools 3.13.1.v20171009-0410 (org.eclipse.jdt.feature.group 3.13.1.v20171009-0410)
    To: org.eclipse.jdt.core [3.13.50.v20171007-0855]

**Comment by svenjawendler** [comment]
Also two of my collegues have this problem: We also cannot update to To: org.eclipse.jdt.core [3.14.0.v20171025-0549].

**Comment by ivica7** [comment]
Same problem here on Mac OSX 10.13.1 with Eclipse Oxygen.1a Release (4.7.1a)

**Comment by andreasmuelder** [comment]
Fixed, thanks for reporting
