### ISSUE TITLE
returnsize not recognized in solidity assembly

### ISSUE THREAD

**Issue by ivica7** [Yakindu/solidity-ide#84]
The new solidity assembly command ``returnsize`` is not recognized.

**Comment by andreasmuelder** [comment]
Can you provide an example on this with the error message? Since we do not parse the inline assembly yet, it should work.

**Comment by ivica7** [comment]
see the last line in the assembly code:
```
assembly {
            let _target := t
            calldatacopy(0x0, 0x0, calldatasize) 
            let retval := delegatecall(gas, _target, 0x0, calldatasize, 0x0, 0)
            let returnsize := returndatasize
            returndatacopy(0x0, 0x0, returnsize)
            switch retval case 0 {revert(0, 0)} default {return (0, returnsize)}
        }
```

**Comment by andreasmuelder** [comment]
Thanks I can reproduce this now. Problem here was the 'return' that was identified as keyword, this should be escaped now.
