### ISSUE TITLE
Question: how to create a solidity project from scratch via New-Wizard?

### ISSUE THREAD

**Issue by ivica7** [Yakindu/solidity-ide#86]
I see that New wizard is offering "New Solidity File" but there is nothing like "New Solidity Project".

**Comment by andreasmuelder** [comment]
Create a new general project and create a .sol file in this project.
We should provide a new Solidity project wizard.

**Comment by ivica7** [comment]
The "New Solidity File" Wizard is not working, but I can create a generic file with the .sol extension.

**Comment by andreasmuelder** [comment]
Closing this, the new file wizard problem is covered by #85
