### ISSUE TITLE
implicit type conversion malfunction

### ISSUE THREAD

**Issue by godmonth** [Yakindu/solidity-ide#95]
implicit type conversion indicate error, code below:
using SafeMath for uint256;
x.sub(y)

error message :
Wrong number of arguments, expected [ (name: a type: uint256) (storage: memory),  (name: b type: uint256) (storage: memory)] .

**Comment by andreasmuelder** [comment]
this is related to #26

**Comment by andreasmuelder** [comment]
fixed
